_target_: src.models.image_classification.ImageClassification

initializer:
  _target_: src.initializers.mean_field.MeanFieldInitializer
  num_layers: ${model.net.num_hidden_layers}
  initialization: "critical"

optimizer:
  _target_: torch_optimizer.DiffGrad
  _partial_: true
  lr: 0.0001

scheduler: null

net:
  _target_: src.models.components.convolutional.ConvolutionalNet
  input_shape: [1, 28, 28]
  num_conv_channels: 32
  num_hidden_layers: 20
  num_classes: 10
