# https://neptune.ai

neptune:
  _target_: pytorch_lightning.loggers.neptune.NeptuneLogger
  api_key: ${oc.env:NEPTUNE_API_TOKEN} # api key is loaded from environment variable
  project: astroviking/master-thesis-project
  # name: ""
  log_model_checkpoints: True
  prefix: ""
