# @package _global_

defaults:
  - _self_
  - data: mnist
  - logger: null
  - paths: default
  - extras: default
  - hydra: default
  - comparator: default

task_name: "compare"

tags: ["dev"]

models:
  group:
    - model.net.num_hidden_layers
  compare:
    - model.initializer.initialization
  combine:
    - seed
  search_paths:
    - ???
